### ISSUE TITLE
Look into type parameters

### ISSUE THREAD

**Issue by jcward** [derRaab/de-superclass-haxe#1]
Hi @derRaab, cool tools, thanks for sharing!

FYI, for the ArrayUtil (maybe others?), you should look at using type generics in your functions. This would make their usage more type-safe. For example:

![image](https://cloud.githubusercontent.com/assets/2192439/26263256/46871558-3c95-11e7-9d67-ead63a1483a8.png)

Example: https://try.haxe.org/#5961A

Cheers,
-Jeff

**Comment by derRaab** [comment]
Thanks Jeff, I tried my best and pushed an update for ArrayUtil. Great hint!

**Comment by jcward** [comment]
Looks good, nice job!

**Comment by derRaab** [comment]
Cool. :)
